# Generated by Django 4.0.2 on 2023-02-18 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cf7097b5-5079-4faf-8590-8a331e5e4280'), editable=False, primary_key=True, serialize=False),
        ),
    ]
