# Generated by Django 4.0.2 on 2023-02-22 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('n', 'Новый'), ('u', 'Б/у')], default='n', max_length=5, verbose_name='Состояние товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('s', 'Продажа'), ('e', 'Обмен'), ('f', 'Даром')], default='s', max_length=5, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b664f284-e2bc-436c-9f75-d645d2fb61a8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
    ]
