# Generated by Django 4.0.2 on 2023-02-22 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c95fba0d-9ec6-4056-8d18-4f81c67cef80'), editable=False, primary_key=True, serialize=False),
        ),
    ]
