# Generated by Django 4.0.2 on 2023-03-04 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_product_id_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('16594cfa-f1a6-42d7-b689-db2a8f07b075'), editable=False, primary_key=True, serialize=False),
        ),
    ]
