# Generated by Django 4.0.2 on 2023-03-16 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1131e6b0-1fed-481c-b1c8-f3138524b988'), editable=False, primary_key=True, serialize=False),
        ),
    ]
