# Generated by Django 4.0.2 on 2023-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_actived',
            field=models.BooleanField(default=False),
        ),
    ]
